highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
auto: true
safe: false
url: http://biomadeira.github.io/
title: Fábio Madeira
author:
    name: Fábio Madeira
    email: fabiomadeira@me.com
    github: biomadeira
    twitter: biomadeira