
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


url: http://biomadeira.github.io/
basurl: /
title: Fábio Madeira
author: Fábio Madeira
description: Personal blog and resume
email: fabiomadeira@me.com
github: biomadeira
twitter: biomadeira
google_analytics: UA-47728743-1